### PR TITLE
Updated gen model

### PR DESCRIPTION
**Pull request by danich1**
This PR follows the previous pr (#93). I took the time to carefully examine my code and notice a few bugs concerning the generative model performance:
1. The grid search algorithm wasn't selecting the best model. It was selecting a model at random. Fixed that and then I realized I was using the wrong column to estimate model performance. 
2. The indices for the GiG and possibly CbG relation had an added label function that shouldn't be in there.

After fixing the above bugs I have corrected the gen model's auroc and aupr point plot grid:

| Before Bug Fix | After Bug Fix |
| --- | --- |
| [tune set AUROC](https://raw.githubusercontent.com/greenelab/snorkeling/dd70fd47933e3ceebbef1c7f4990454ff4807904/figures/label_sampling_experiment/transfer_dev_set_auroc.png) | [tune set AUROC](https://raw.githubusercontent.com/danich1/snorkeling/52a2ae71fbc82159342bc68b1712a38ecf53ff45/figures/label_sampling_experiment/transfer_dev_set_auroc.png)  | 
| [tune set AUPR](https://raw.githubusercontent.com/greenelab/snorkeling/dd70fd47933e3ceebbef1c7f4990454ff4807904/figures/label_sampling_experiment/transfer_dev_set_auprc.png)  | [tune set AUPR](https://raw.githubusercontent.com/danich1/snorkeling/52a2ae71fbc82159342bc68b1712a38ecf53ff45/figures/label_sampling_experiment/transfer_dev_set_auprc.png) |
| [test set AUROC](https://raw.githubusercontent.com/greenelab/snorkeling/dd70fd47933e3ceebbef1c7f4990454ff4807904/figures/label_sampling_experiment/transfer_test_set_auroc.png) | [test set AUROC](https://raw.githubusercontent.com/danich1/snorkeling/52a2ae71fbc82159342bc68b1712a38ecf53ff45/figures/label_sampling_experiment/transfer_test_set_auroc.png) | 
| [tune set AUPR](https://raw.githubusercontent.com/greenelab/snorkeling/dd70fd47933e3ceebbef1c7f4990454ff4807904/figures/label_sampling_experiment/transfer_test_set_auprc.png) | [test set AUPR](https://raw.githubusercontent.com/danich1/snorkeling/52a2ae71fbc82159342bc68b1712a38ecf53ff45/figures/label_sampling_experiment/transfer_test_set_auprc.png) | 

Lastly, this means that the spike I was observing within the GiG and CbG relations was just a bug.. **Anyway for this review take a look at the updated figures and notebooks and the `train_model_helpher.py` file.** The other files have quick one liner changes.

 After this PR, there will be another one that just contains the updated data files. Didn't want to risk this PR getting too large.

### CODE REVIEW

**Comment by cgreene** [comment]
Some of those figures listed above seem to have 404s.

**Comment by danich1** [comment]
Ah Fixed. There was a missing c in the file name.

**Review by dhimmel — APPROVED** [review]
conceptual acknowledgement: nice job finding bug.

Looks like code in `modules/utils/notebook_utils/train_model_helper.py` now has reduced cyclomatic complexity and length which is good. Still there are some references by index rather than name, which is a more error-prone construct. Something to keep in mind for future.

**Review by ajlee21 — APPROVED** [review]
Glad you found the bugs!

The curves look great!  It looks like your current model is very robust - very small confidence intervals and the curves are more smooth which makes sense.

For the future, I wonder if it would help to add some more comments to your scripts to help you to mentally slow down a little to make sure everything makes sense?  Perhaps you have your own system though.

**Pull request merged**
