### PR TITLE
Upgrade environment to use snorkel v0.5

### PR DESCRIPTION
**Pull request by danich1**
Closes https://github.com/greenelab/snorkeling/issues/5

### CODE REVIEW

**Comment by dhimmel** [comment]
Here's a screenshot of how snorkel's `python-package-requirement.txt` [changes](https://github.com/HazyResearch/snorkel/compare/e49ecb2047327173ed56b2f85d4a71bdc4487bbc...c8a8d2377fe0f5d71cc078cd5368ac6f3b33a433#diff-1ea4f291a781edb002629c1df453f251) with the submodule update.

python-package-requirement.txt

As far as I can tell, the only change is that `theano` has been replaced by `tensorflow`. @ajratner will all uses need `tensorflow`? @danich1 so I think we should remove `theano` (check nothing breaks) and potentially add `tensorflow`, although we can hold off installing that until we need it, if you would like. Let's wait to hear from @ajratner.

**Comment by ajratner** [comment]
@dhimmel Yes we moved all the default end extraction models to TF in this release, so this would be the right way to go!

**Comment by dhimmel** [comment]
@danich1 let's see if [tensorflow installs](https://www.tensorflow.org/get_started/os_setup#anaconda_installation) with `pip`. Otherwise, we can use conda and add the `conda-forge` channel to our `environment.yml`.

**Comment by danich1** [comment]
Added the tensorflow install line. Pip installs it like a charm!!!

**Review by dhimmel — APPROVED** [review]

**Pull request merged**
